### ISSUE TITLE
Excluding all delete action taking whole day

### ISSUE THREAD

**Issue by SouravG94-312** [gavincampbell-dev-example-repos/FilteringDemo#1]
Hi, I'm try to extend this solution where i need to exclude all delete operation. below is the code snippet after modification, but it's never ending. Let me know if my approach is correct. 

`
$comparisonResult.Differences | %{
		if($_.UpdateAction -eq "Delete") {
			$comparisonResult.Exclude($_) | Out-Null
	}
}
`

**Comment by gavincampbell** [comment]
not sure, I'm a bit busy with client work right now. Will try to come back to this.
